tasks:
  - name: bash
    before: |
      curl -Ls "https://dtsx.io/get-astra-cli" | bash
      . ~/.bashrc
    command: |
      cd /workspace/workshop-ai-as-api
      clear
      echo -e "\n\n\t\t** READY TO START... **\n\n"
  - name: api-shell
    before: |
      cd /workspace/workshop-ai-as-api
      python -m pip install --upgrade pip
      pip install -r requirements.txt 2>&1 > install.log
    command: |
      cd /workspace/workshop-ai-as-api
      clear
      echo -e "\n\n\t\t** READY TO START... **\n\n"
      gp open README.md
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: false
ports:
  - port: 8000
    onOpen: ignore
    visibility: public
