tasks:
  - name: notebook-shell
    before: |
      cd /workspace/workshop-ai-as-api
      python -m pip install --upgrade pip
      pip install -r requirements.txt 2>&1 > install.log
      mkdir -p /home/gitpod/.jupyter
      echo "# Configuration file for jupyter-notebook." >> /home/gitpod/.jupyter/jupyter_notebook_config.py
      echo "# See: https://jupyter-notebook.readthedocs.io/en/stable/config.html" >> /home/gitpod/.jupyter/jupyter_notebook_config.py
      echo "" >> /home/gitpod/.jupyter/jupyter_notebook_config.py
      echo "c = get_config()  # noqa" >> /home/gitpod/.jupyter/jupyter_notebook_config.py
      echo "c.NotebookApp.allow_origin = '*'" >> /home/gitpod/.jupyter/jupyter_notebook_config.py
    command: |
      cd /workspace/workshop-ai-as-api
      jupyter notebook --no-browser --NotebookApp.password='sha1:4964484fac7e:73ca028097aae542f45628a09b3da9c6e4168f6f'
  - name: curl-shell
    before: |
      cd /workspace/workshop-ai-as-api
    command: |
      cd /workspace/workshop-ai-as-api
      clear
      echo -e "\n\n\t\t** READY TO START... **\n\n"
      gp open README.md
  - name: work-shell
    before: |
      curl -Ls "https://dtsx.io/get-astra-cli" | bash
      . ~/.bashrc
    command: |
      cd /workspace/workshop-ai-as-api
      clear
      echo -e "\n\n\t\t** READY TO START... **\n\n"
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: false
ports:
  - port: 8000
    onOpen: ignore
    visibility: public
